In [1]:
import pandas as pd
import random
from datetime import datetime, timedelta

In [2]:
random.seed(42)

In [3]:
DATA_START = pd.Timestamp("2026-01-01")
DATA_END = pd.Timestamp("2026-09-30")

In [4]:
CUSTOMER_START = pd.Timestamp("2026-01-01")
CUSTOMER_END = pd.Timestamp("2026-08-31")

Table Creation
1. Customers

In [13]:
first_names = [
    "Aarav", "Aditi", "Aisha", "Akash", "Ananya","Arjun", "Diya", "Ishaan", "Kabir", "Kavya","Kiara", "Meera", "Neha", "Pooja", "Rahul",
    "Rhea", "Rohan", "Saanvi", "Simran", "Tanvi"
]

last_names = [
    "Sharma", "Verma", "Gupta", "Mehta", "Kapoor","Malhotra", "Jain", "Agarwal", "Khanna", "Bansal"
]

In [6]:
customers = []

for i in range(1, 201):

    platform_user_id = f"PLAT{900000 + i}"

    name = f"{random.choice(first_names)} {random.choice(last_names)}"

    created_at = CUSTOMER_START + pd.Timedelta(
        days=random.randint(
            0,
            (CUSTOMER_END - CUSTOMER_START).days
        )
    )

    customers.append({
        "platform_user_id": platform_user_id,
        "name": name,
        "created_at": created_at
    })

customers_df = pd.DataFrame(customers)

In [10]:
print('head:',customers_df.head())
print('shape:',customers_df.shape)
print('duplicates:',customers_df["platform_user_id"].duplicated().sum())
print('nulls:',customers_df.isnull().sum())

head:   platform_user_id          name created_at
0       PLAT900001  Akash Sharma 2026-07-09
1       PLAT900002   Kabir Mehta 2026-02-27
2       PLAT900003  Ananya Verma 2026-06-23
3       PLAT900004  Saanvi Verma 2026-06-01
4       PLAT900005  Pooja Sharma 2026-01-08
shape: (200, 3)
duplicates: 0
nulls: platform_user_id    0
name                0
created_at          0
dtype: int64

Table Creation
2. Products

In [20]:
categories = [
    "Dresses","Tops","Co-ords","Kurtas","Bottoms","Jackets"
]

materials_by_category = {
    "Dresses": [
        "Cotton", "Linen", "Rayon", "Viscose","Polyester", "Silk Blend", "Chanderi", "Georgette"
    ],
    "Tops": [
        "Cotton", "Linen", "Rayon", "Viscose","Polyester", "Silk Blend", "Knit"
    ],
    "Co-ords": [
        "Cotton", "Linen", "Rayon", "Viscose","Polyester", "Silk Blend"
    ],
    "Kurtas": [
        "Cotton", "Rayon", "Viscose","Silk Blend", "Chanderi"
    ],
    "Bottoms": [
        "Cotton", "Linen", "Viscose","Denim", "Polyester"
    ],
    "Jackets": [
        "Denim", "Cotton", "Polyester", "Knit"
    ]
}

In [ ]:
product_names = {
    "Dresses": [
        "Floral Midi Dress","Wrap Dress","A-Line Dress","Pleated Maxi Dress","Ruched Party Dress"
    ],
    "Tops": [
        "Cotton Shirt","Ribbed Top","Satin Blouse","Printed Top","Crop Shirt"
    ],
    "Co-ords": [
        "Linen Co-ord Set","Printed Co-ord Set","Relaxed Co-ord Set","Embroidered Co-ord Set","Party Co-ord Set"
    ],
    "Kurtas": [
        "Straight Kurta","A-Line Kurta","Printed Kurta","Embroidered Kurta","Festive Kurta"
    ],
    "Bottoms": [
        "Wide-Leg Trousers","Straight Pants","Palazzo Pants","Denim Jeans","Pleated Skirt"
    ],
    "Jackets": [
        "Denim Jacket","Cropped Jacket","Utility Jacket","Quilted Jacket","Lightweight Blazer"
    ]
}

prices = [
    799, 999, 1199, 1299, 1499,1699, 1899, 1999, 2199,2499, 2799, 2999, 3299, 3499
]

In [21]:
products = []

for i in range(1, 101):

    category = random.choice(categories)
    base_name = random.choice(product_names[category])

    products.append({
        "product_id": f"P{i:03d}",
        "product_name": f"{base_name} {i:02d}",
        "category": category,
        "price": random.choice(prices),
        "material": random.choice(materials_by_category[category]),
        "active_status": random.choices(
            ["Active", "Inactive"],
            weights=[85, 15]
        )[0]
    })

products_df = pd.DataFrame(products)

In [23]:
print('head:',products_df.head(10))
print('shape:',products_df.shape)
print('category count:',products_df["category"].value_counts())
print('status count:',products_df["active_status"].value_counts())
print('product_id duplicates:',products_df["product_id"].duplicated().sum())

head:   product_id           product_name category  price    material active_status
0       P001       Printed Kurta 01   Kurtas   1699    Chanderi        Active
1       P002   Embroidered Kurta 02   Kurtas   1699       Rayon      Inactive
2       P003          Crop Shirt 03     Tops   1899       Linen      Inactive
3       P004      Straight Kurta 04   Kurtas   1699  Silk Blend        Active
4       P005   Embroidered Kurta 05   Kurtas   2799       Rayon        Active
5       P006          Wrap Dress 06  Dresses   2199  Silk Blend      Inactive
6       P007      Straight Kurta 07   Kurtas   2199  Silk Blend        Active
7       P008         Printed Top 08     Tops   3499  Silk Blend      Inactive
8       P009  Pleated Maxi Dress 09  Dresses   3299   Polyester        Active
9       P010      Quilted Jacket 10  Jackets   2799       Denim      Inactive
shape: (100, 6)
category count: category
Kurtas     23
Dresses    18
Jackets    18
Co-ords    15
Tops       14
Bottoms    12
Name: count, dtype: int64
status count: active_status
Active      85
Inactive    15
Name: count, dtype: int64
product_id duplicates: 0

Table Creation
3. Product Variants

In [25]:
colors = [
    "Black", "White", "Blue", "Green", "Pink","Red", "Beige", "Brown", "Yellow", "Grey"
]

sizes = ["XS", "S", "M", "L", "XL"]

In [26]:
product_variants = []
variant_counter = 1

for _, row in products_df.iterrows():

    product_id = row["product_id"]

    selected_colors = random.sample(colors, 2)

    for colour in selected_colors:

        for size in sizes:

            stock_qty = random.randint(0, 20)

            product_variants.append({
                "variant_id": f"V{variant_counter:04d}",
                "product_id": product_id,
                "colour": colour,
                "size": size,
                "stock_qty": stock_qty
            })

            variant_counter += 1

variants_df = pd.DataFrame(product_variants)

In [29]:
variants_df.head(10)

  variant_id product_id colour size  stock_qty
0      V0001       P001  Beige   XS          3
1      V0002       P001  Beige    S         12
2      V0003       P001  Beige    M          0
3      V0004       P001  Beige    L         10
4      V0005       P001  Beige   XL          5
5      V0006       P001   Pink   XS         19
6      V0007       P001   Pink    S         14
7      V0008       P001   Pink    M         11
8      V0009       P001   Pink    L          2
9      V0010       P001   Pink   XL         13

In [ ]:
variants_df.shape

(1000, 5)

In [ ]:
print("Duplicate variant IDs:",
      variants_df["variant_id"].duplicated().sum())

print("All product IDs valid:",
      variants_df["product_id"].isin(
          products_df["product_id"]
      ).all())

print("Out of stock:",
      (variants_df["stock_qty"] == 0).sum())

print("Low stock:",
      variants_df["stock_qty"].between(1, 5).sum())

print("Normal stock:",
      (variants_df["stock_qty"] > 5).sum())

Duplicate variant IDs: 0
All product IDs valid: True
Out of stock: 30
Low stock: 237
Normal stock: 733

Table Creation
4. Orders

In [30]:
reference_date = pd.Timestamp("2026-09-30")

orders = []

for i in range(1, 501):

    customer = customers_df.sample(1).iloc[0]

    platform_user_id = customer["platform_user_id"]
    customer_created_at = customer["created_at"]

    # 15% recent active-order candidates
    is_recent = random.random() < 0.15

    if is_recent:
        order_start = max(
            customer_created_at,
            reference_date - pd.Timedelta(days=7)
        )

        order_date = order_start + pd.Timedelta(
            days=random.randint(
                0,
                (reference_date - order_start).days
            )
        )

        days_old = (reference_date - order_date).days

        if days_old <= 1:
            order_status = random.choice(["Placed", "Processing"])

        elif days_old <= 3:
            order_status = random.choice(["Processing", "Shipped"])

        elif days_old <= 5:
            order_status = random.choice(["Shipped", "Out for Delivery"])

        else:
            order_status = random.choice(
                ["Out for Delivery", "Delivered"]
            )

    else:
        order_date = customer_created_at + pd.Timedelta(
            days=random.randint(
                0,
                (reference_date - customer_created_at).days
            )
        )

        order_status = random.choices(
            ["Delivered", "Cancelled"],
            weights=[85, 15]
        )[0]

    expected_delivery_date = (
        order_date + pd.Timedelta(days=random.randint(3, 8))
    )

    orders.append({
        "order_id": f"ORD{i:04d}",
        "platform_user_id": platform_user_id,
        "order_date": order_date,
        "order_status": order_status,
        "expected_delivery_date": expected_delivery_date
    })

orders_df = pd.DataFrame(orders)

In [31]:
orders_df.head(10)

  order_id platform_user_id order_date order_status expected_delivery_date
0  ORD0001       PLAT900003 2026-09-29       Placed             2026-10-02
1  ORD0002       PLAT900150 2026-08-27    Delivered             2026-09-01
2  ORD0003       PLAT900041 2026-09-29       Placed             2026-10-02
3  ORD0004       PLAT900147 2026-07-07    Delivered             2026-07-11
4  ORD0005       PLAT900076 2026-07-02    Delivered             2026-07-07
5  ORD0006       PLAT900098 2026-03-16    Delivered             2026-03-22
6  ORD0007       PLAT900017 2026-07-19    Cancelled             2026-07-23
7  ORD0008       PLAT900117 2026-03-29    Delivered             2026-04-06
8  ORD0009       PLAT900147 2026-03-18    Delivered             2026-03-24
9  ORD0010       PLAT900187 2026-06-25    Delivered             2026-07-03

In [32]:
print("Shape:", orders_df.shape)

print(
    orders_df["order_status"].value_counts()
)

print(
    "Orders before customer creation:",
    (
        orders_df.merge(
            customers_df[
                ["platform_user_id", "created_at"]
            ],
            on="platform_user_id"
        )["order_date"]
        <
        orders_df.merge(
            customers_df[
                ["platform_user_id", "created_at"]
            ],
            on="platform_user_id"
        )["created_at"]
    ).sum()
)

Shape: (500, 5)
order_status
Delivered           385
Cancelled            47
Out for Delivery     21
Processing           19
Shipped              18
Placed               10
Name: count, dtype: int64
Orders before customer creation: 0

In [33]:
active_statuses = [
    "Placed",
    "Processing",
    "Shipped",
    "Out for Delivery"
]

old_active_orders = orders_df[
    orders_df["order_status"].isin(active_statuses)
    &
    (
        orders_df["order_date"]
        <
        reference_date - pd.Timedelta(days=7)
    )
]

print("Old active orders:", len(old_active_orders))

Old active orders: 0

In [34]:
print(
    "Duplicate order IDs:",
    orders_df["order_id"].duplicated().sum()
)

print(
    "Null values:"
)
print(orders_df.isnull().sum())

Duplicate order IDs: 0
Null values:
order_id                  0
platform_user_id          0
order_date                0
order_status              0
expected_delivery_date    0
dtype: int64

Table Creation
5. Order Items

In [35]:
order_items = []
order_item_counter = 1

for order_id in orders_df["order_id"]:

    number_of_items = random.randint(1, 3)

    selected_variants = variants_df.sample(
        n=number_of_items,
        replace=False
    )

    for _, variant in selected_variants.iterrows():

        variant_id = variant["variant_id"]
        product_id = variant["product_id"]

        quantity = random.randint(1, 2)

        unit_price = products_df.loc[
            products_df["product_id"] == product_id,
            "price"
        ].iloc[0]

        order_items.append({
            "order_item_id": f"OI{order_item_counter:05d}",
            "order_id": order_id,
            "variant_id": variant_id,
            "quantity": quantity,
            "unit_price": unit_price
        })

        order_item_counter += 1

order_items_df = pd.DataFrame(order_items)

In [37]:
order_items_df.head(10)

  order_item_id order_id variant_id  quantity  unit_price
0       OI00001  ORD0001      V0367         1        3499
1       OI00002  ORD0001      V0192         2        2799
2       OI00003  ORD0002      V0750         2        3299
3       OI00004  ORD0002      V0343         1        3299
4       OI00005  ORD0003      V0912         2        1899
5       OI00006  ORD0004      V0940         1         799
6       OI00007  ORD0005      V0765         2        3499
7       OI00008  ORD0005      V0783         2        1299
8       OI00009  ORD0005      V0026         2        1899
9       OI00010  ORD0006      V0108         2        1899

In [ ]:

print("Shape:", order_items_df.shape)

print(
    "Duplicate order_item_id:",
    order_items_df["order_item_id"].duplicated().sum()
)

print(
    "All order IDs valid:",
    order_items_df["order_id"].isin(
        orders_df["order_id"]
    ).all()
)

print(
    "All variant IDs valid:",
    order_items_df["variant_id"].isin(
        variants_df["variant_id"]
    ).all()
)

print(order_items_df.isnull().sum())

Shape: (1004, 5)
Duplicate order_item_id: 0
All order IDs valid: True
All variant IDs valid: True
order_item_id    0
order_id         0
variant_id       0
quantity         0
unit_price       0
dtype: int64

Table creation
6. Messages

In [38]:
intents = [
    "Product Information","Inventory Check","Order Tracking","Shipping Query","Human Support"
]

In [39]:
message_templates = {
    "Product Information": [
        "What is the price of this product?",
        "What material is this?",
        "What colours are available?",
        "Can you tell me more about this item?"
    ],

    "Inventory Check": [
        "Is this available in M?",
        "Do you have this in black?",
        "Is size L available?",
        "Is this currently in stock?"
    ],

    "Order Tracking": [
        "Where is my order?",
        "Can you check my order status?",
        "Has my order been shipped?",
        "When will my order arrive?"
    ],

    "Shipping Query": [
        "How long does delivery usually take?",
        "How many days does shipping take?",
        "Do you deliver across India?",
        "What is the usual delivery time?"
    ],

    "Human Support": [
        "I want to return my order.",
        "I want a refund.",
        "My product arrived damaged.",
        "I received the wrong item.",
        "I want to cancel my order.",
        "Please connect me with customer support."
    ]
}

In [40]:
messages = []

for i in range(1, 601):

    customer = customers_df.sample(1).iloc[0]

    platform_user_id = customer["platform_user_id"]
    customer_created_at = customer["created_at"]

    intent = random.choice(intents)

    message_text = random.choice(
        message_templates[intent]
    )

    message_date = customer_created_at + pd.Timedelta(
        days=random.randint(
            0,
            (DATA_END - customer_created_at).days
        ),
        hours=random.randint(0, 23),
        minutes=random.randint(0, 59)
    )

    if intent in ["Product Information", "Inventory Check"]:
        current_product_id = random.choice(
            products_df["product_id"].tolist()
        )
    else:
        current_product_id = None

    messages.append({
        "message_id": f"MSG{i:05d}",
        "platform_user_id": platform_user_id,
        "sender_type": "Customer",
        "message_text": message_text,
        "intent": intent,
        "timestamp": message_date,
        "current_product_id": current_product_id
    })

messages_df = pd.DataFrame(messages)

In [41]:
messages_df.head(10)

,message_id,platform_user_id,sender_type,message_text,intent,timestamp,current_product_id
0,MSG00001,PLAT900149,Customer,How long does delivery usually take?,Shipping Query,2026-07-22 15:29:00,None
1,MSG00002,PLAT900036,Customer,Is size L available?,Inventory Check,2026-09-06 19:36:00,P017
2,MSG00003,PLAT900107,Customer,I want to return my order.,Human Support,2026-08-20 22:50:00,None
3,MSG00004,PLAT900058,Customer,What colours are available?,Product Information,2026-09-28 20:04:00,P039
4,MSG00005,PLAT900116,Customer,I received the wrong item.,Human Support,2026-06-04 18:26:00,None
5,MSG00006,PLAT900042,Customer,Do you have this in black?,Inventory Check,2026-09-28 05:30:00,P050
6,MSG00007,PLAT900188,Customer,What colours are available?,Product Information,2026-07-04 22:37:00,P056
7,MSG00008,PLAT900045,Customer,Do you deliver across India?,Shipping Query,2026-08-10 22:15:00,None
8,MSG00009,PLAT900161,Customer,Is this available in M?,Inventory Check,2026-09-29 18:53:00,P063
9,MSG00010,PLAT900010,Customer,Can you tell me more about this item?,Product Information,2026-06-04 17:06:00,P057

In [42]:
print("Shape:", messages_df.shape)

print(
    "Duplicate message IDs:",
    messages_df["message_id"].duplicated().sum()
)

print(
    "All platform IDs valid:",
    messages_df["platform_user_id"].isin(
        customers_df["platform_user_id"]
    ).all()
)

print(
    "All product IDs valid:",
    messages_df["current_product_id"].dropna().isin(
        products_df["product_id"]
    ).all()
)

print(messages_df["intent"].value_counts())

Shape: (600, 7)
Duplicate message IDs: 0
All platform IDs valid: True
All product IDs valid: True
intent
Shipping Query         130
Human Support          128
Product Information    121
Inventory Check        117
Order Tracking         104
Name: count, dtype: int64

In [43]:
messages_check = messages_df.merge(
    customers_df[
        ["platform_user_id", "created_at"]
    ],
    on="platform_user_id"
)

print(
    "Messages before customer creation:",
    (
        messages_check["timestamp"]
        <
        messages_check["created_at"]
    ).sum()
)

Messages before customer creation: 0

In [44]:
customers_df.to_csv("customers.csv", index=False)
products_df.to_csv("products.csv", index=False)
variants_df.to_csv("product_variants.csv", index=False)
orders_df.to_csv("orders.csv", index=False)
order_items_df.to_csv("order_items.csv", index=False)
messages_df.to_csv("messages.csv", index=False)